import Foundation

/// Response from LLM for profile generation
struct ProfileGenerationResponse: Codable {
    /// Identified interests from video interactions
    let interests: [InterestGeneration]
    /// Natural language description of the user's profile
    let description: String
}

/// Interest as generated by the LLM
struct InterestGeneration: Codable {
    /// The main topic of interest
    let topic: String
    /// Example activities or aspects of this interest
    let examples: [String]
} 