/// Base protocol for all prompt types
protocol Prompt {
    /// The actual prompt text
    var prompt: String { get }
    /// Optional array of parent prompt IDs
    var parentIds: [String]? { get }
}

/// A prompt generated by mutating an existing prompt
struct MutationPrompt: Prompt {
    let prompt: String
    let parentId: String
    
    var parentIds: [String]? {
        [parentId]
    }
}

/// A prompt generated by combining two existing prompts
struct CrossoverPrompt: Prompt {
    let prompt: String
    let parentIds: [String]?
}

/// A prompt generated based on user profile interests
struct ProfileBasedPrompt: Prompt {
    let prompt: String
    var parentIds: [String]? { nil }
}

/// A randomly generated prompt for exploration
struct RandomPrompt: Prompt {
    let prompt: String
    var parentIds: [String]? { nil }
} 